FROM nginx:1.25-alpine
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/educhat.conf
COPY static/ /usr/share/nginx/html/static/
COPY static/index.html /usr/share/nginx/html/index.html
RUN echo "=== Contenu /usr/share/nginx/html/ ===" && \
    find /usr/share/nginx/html/ -type f

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]