sonar.projectKey=DhekraBalbouli_Educhat_Project_DEVOPS
sonar.organization=dhekrabalbouli
sonar.python.version=3.11

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=Educhat_Project_DEVOPS
#sonar.projectVersion=1.0
sonar.sources=chatbot,api
sonar.exclusions=**/__pycache__/**,**/*.pyc,venv/**,.venv/**,reports/**
# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8